#!/bin/sh

echo "\nGet dependencies"
echo "================\n"

npm install
bower install

echo "\n\nInitializing project"
echo "====================\n"

git clone https://github.com/pattern-lab/patternlab-php.git && \
mv patternlab-php/config/ .                                 && \
mv patternlab-php/core/ .                                   && \
mv patternlab-php/extras/ .                                 && \
mv patternlab-php/public/ .                                 && \
rm -rf patternlab-php                                       && \
rm -rf source/assets                                           && \
php core/builder.php -g                                     && \
rm -rf source/css                                           && \
git submodule init                                          && \
git submodule update                                        && \
cd source/assets/scss/                                      && \
git pull origin master                                      && \
cd ../../../                                                && \
rm source/favicon.ico                                       && \
rm -rf source/assets/scss/.git                              && \
# rm -rf .git/                                                && \
# rm -rf .gitmodules                                          && \
rm -rf source/css/                                          && \
rm -rf source/js/                                           && \
rm -rf source/fonts/                                        && \
mkdir source/assets/fonts/                                  && \
> source/assets/fonts/.gitkeep                              && \
mkdir source/assets/images/                                 && \
> source/assets/images/.gitkeep                             && \
mkdir source/assets/js/                                     && \
> source/assets/js/script.js

echo "\nPattern Lab is now beautifully scaffolded"

rm init
