#!/bin/sh

echo "\nGet dependencies"
echo "================\n"

npm install
bower install

echo "\n\nInitializing project"
echo "====================\n"

# Install Pattern Lab Standard Edition for Twig
composer create-project pattern-lab/edition-twig-standard . && \

# Generate Pattern Lab for the first time
php core/console --generate                                 && \

# Get Git submodule(s)
git submodule init                                          && \
git submodule update                                        && \
cd source/assets/scss/                                      && \
git pull origin master                                      && \
# rm -rf .git                                                 && \
# rm -rf .gitignore                                           && \
cd ../../../                                                && \

# Remove no longer needed project Git repository
# rm -rf .git/                                                && \
# rm -rf .gitmodules                                          && \

# Delete Pattern Lab source files
rm source/favicon.ico                                       && \
rm -rf source/css/                                          && \
rm -rf source/js/                                           && \
# rm -rf source/image/                                        && \

# Create assets directories
mkdir source/assets/fonts/                                  && \
> source/assets/fonts/.gitkeep                              && \
mkdir source/assets/images/                                 && \
> source/assets/images/.gitkeep                             && \
mkdir source/assets/icons/                                  && \
> source/assets/icons/.gitkeep                              && \
mkdir source/assets/js/                                     && \
> source/assets/js/script.js

# Finalize
# rm README.md                                                && \
# mv README.final.md README.md                                && \


echo ""
echo "================================================"
echo "=  Pattern Lab is now beautifully scaffolded!  ="
echo "================================================"

# Finalize and delete not longer needed files
# rm README.md                                                && \
# mv README.final.md README.md                                && \
# mv LICENSE                                                  && \
# rm init-dev                                                 && \
# rm init
